baseURL = "https://NilBrahim.github.io/"
languageCode = "en-us"
title = "Niloofar Ebrahimi"
mainSections = ["Blog"]
theme = "hugo-blog-awesome"
[markup.goldmark.renderer]
  unsafe = true

[params]
  defaultTheme = "light"
  ShowPostDate = false
customCSS = ["css/custom.css"]
  

 

[params.style]
  themeColor = "auto"   # "light", "dark", or "auto"
  primaryColor = "#4B7BAE"


[[params.socialIcons]]
icon = "linkedin"
url = "https://www.linkedin.com/in/niloufar-ebrahimi/"

[[params.socialIcons]]
icon = "github"
url = "https://github.com/NilBrahim"

[[params.socialIcons]]
icon = "mail"
url = "mailto:s.niloufar.ebrahimi@gmail.com"


[[menu.main]]
  name = "Resources"
  url = "/resources/"
  weight = 1

[[menu.main]]
  name = "Reading List"
  url = "/reading-list/"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 3


